- CHANGELOG.md
- README.md
- `composer.json` instructions updated to bring the possibility to install via https 
- Changelog updated
> [SN-682] docs: update README and CHANGELOG

- src/Factory/Xml/Category/CategoryAttributeFactory.php
- tests/Unit/Category/CategoryAttributeTest.php
Master coverage
Classes: 93.40% (99/106)   
Methods: 97.59% (446/457)  
Lines:   93.08% (2637/2833)
Branch coverage
Classes: 93.40% (99/106)   
Methods: 97.59% (446/457)  
Lines:   93.08% (2637/2833)
> [SN-746] fix: return null if category attribute maxLength is not set

- src/Model/Feed/FeedError.php
- tests/Functional/FeedManagerTest.php
- tests/Unit/Feed/FeedErrorTest.php
Master coverage
Classes: 93.40% (99/106)
Methods: 97.59% (446/457)
Lines: 93.08% (2637/2833)
Branch coverage
Classes: 93.40% (99/106)   
Methods: 97.59% (446/457)  
Lines:   93.08% (2635/2831)
> [SN-739] fix: remove missing sellerSku feed exception

- CHANGELOG.md
- codefresh.yml
- src/Model/Product/Attribute.php
- src/Model/Product/Product.php
- src/Model/Product/ProductData.php
- src/Transformer/Product/ProductTransformer.php
- tests/Unit/Transformer/Product/ProductTransfomerTest.php
Master coverage: 99% files / 93% lines
Branch coverage: 99% files / 93% lines
> [SN-803] feat: allow user to send partial product data on product update

- CHANGELOG.md
- phpunit.xml.dist
- src/Model/Product/Attribute.php
- src/Model/Product/Product.php
- tests/Unit/Product/ProductTest.php
**Master Coverage**
_Code Coverage Report Summary:_
Classes: 91.51% (97/106)   
Methods: 97.20% (451/464)  
Lines:   93.08% (2665/2863)
**Branch Coverage**
_Code Coverage Report Summary:_
Classes: 91.51% (97/106)   
Methods: 97.21% (453/466)  
Lines:   93.10% (2670/2868)
> [SCP-263]feat: add support to update sku

- CHANGELOG.md
- src/Model/Order/Order.php
- tests/Unit/Order/OrderTest.php
**Master coverage**
_Code Coverage Report Summary:_
Classes: 91.51% (97/106)   
Methods: 97.21% (453/466)  
Lines:   92.97% (2724/2930)
**Branch coverage**
_Code Coverage Report Summary:_
Classes: 91.51% (97/106)   
Methods: 97.22% (454/467)  
Lines:   92.97% (2726/2932)
> [SCP-517] feat: add items setter to order model

- CHANGELOG.md
- composer.json
- composer.lock
- docker-compose.cli.yml
- docs/Contribute/Tests.md
- src/Factory/Xml/Feed/FeedCountFactory.php
- src/Model/Feed/FeedCount.php
- src/Service/FeedManager.php
- tests/Functional/FeedManagerTest.php
- tests/LinioTestCase.php
- tests/Unit/Feed/FeedCountTest.php
- tests/_schemas/FeedCount.xml
**Master branch** 
_Code Coverage Report Summary:_
Classes: 91.51% (97/106)   
Methods: 97.21% (453/466)  
Lines:   92.97% (2724/2930)
**Current branch**
_Code Coverage Report Summary:_
Classes: 91.67% (99/108)   
Methods: 97.27% (464/477)  
Lines:   93.12% (2790/2996)
> [SCP-482] feat: create get feed count method

- CHANGELOG.md
- docs/Managers/Feed.md
- src/Service/BaseManager.php
- src/Service/FeedManager.php
- tests/Functional/FeedManagerTest.php
- tests/Unit/Service/BaseManagerTest.php
Master coverage:
Classes: 91.51% (97/106)   
Methods: 97.21% (453/466)  
Lines:   92.97% (2724/2930)
Branch coverage:
Classes: 91.59% (98/107)   
Methods: 97.26% (461/474)  
Lines:   93.11% (2783/2989)
> [SCP-480] feat: create feed offset list method

- CHANGELOG.md
- docs/Managers/Feed.md
- src/Factory/Xml/FeedResponseFactory.php
- src/Response/FeedResponse.php
- src/Service/FeedManager.php
- src/Validator/XmlStructureValidator.php
- tests/Functional/FeedManagerTest.php
- tests/Unit/Response/FeedResponseTest.php
- tests/Unit/Validator/XmlStructureValidatorTest.php
- tests/_schemas/Feed/FeedCancel.xml
- tests/_schemas/Product/ProductCreate.xml
**Master coverage**
Classes: 91.74% (100/109)  
Methods: 97.33% (473/486)  
Lines:   93.25% (2848/3054)
**Branch coverage**
_Code Coverage Report Summary:_
Classes: 91.82% (101/110)  
Methods: 97.35% (477/490)  
Lines:   93.30% (2867/3073)
> [SCP-483] feat: create feed cancel method

- CHANGELOG.md
**Master coverage**
Classes: 91.74% (100/109)
Methods: 97.33% (473/486)
Lines: 93.25% (2848/3054)
> docs: update CHANGELOG before release

- docker-compose.cli.yml
- docker/Dockerfile
- docker/php.ini
- src/Contract/BusinessUnitOperatorCodes.php
- src/Model/Product/BusinessUnit.php
- tests/Unit/Product/BusinessUnitTest.php
Coverage - Master
Classes: 91.15% (103/113)  
Methods: 97.19% (484/498)  
Lines:   93.34% (2901/3108)
Coverage - feat/SCP-1489-create-businessunit-model
Classes: 91.23% (104/114)  
Methods: 97.31% (506/520)  
Lines:   93.48% (2967/3174)
> [SCP-1489] feat: create businessunit model

- src/Model/Product/BusinessUnits.php
- tests/Unit/Product/BusinessUnitsTest.php
Coverage:
gcs-master: 
Classes: 91.23% (104/114)  
Methods: 97.31% (506/520)  
Lines:   93.48% (2967/3174)aster  
feat/SCP-1490-create-businessunits-model:
Classes: 91.30% (105/115)  
Methods: 97.33% (510/524)  
Lines:   93.50% (2978/3185)
> [SCP-1490] feat: add businessunits model

- src/Factory/Xml/Product/BusinessUnitFactory.php
- src/Factory/Xml/Product/BusinessUnitsFactory.php
- tests/Unit/Product/BusinessUnitTest.php
- tests/Unit/Product/BusinessUnitsTest.php
- tests/_schemas/Product/BusinessUnit.xml
- tests/_schemas/Product/BusinessUnitWithoutIsPublished.xml
- tests/_schemas/Product/BusinessUnitWithoutOperatorCode.xml
- tests/_schemas/Product/BusinessUnitWithoutPrice.xml
- tests/_schemas/Product/BusinessUnitWithoutStatus.xml
- tests/_schemas/Product/BusinessUnitWithoutStock.xml
- tests/_schemas/Product/ProductWithOnlyBusinessUnits.xml
Coverage:
gcs-master:
```
Classes: 91.30% (105/115)
Methods: 97.33% (510/524)  
Lines:   93.50% (2978/3185)
```
feat/SCP-1491-create-businessunit-factory-and-businessunits-factory:
```
Classes: 91.45% (107/117)  
Methods: 97.34% (512/526)  
Lines:   93.58% (3016/3223)
```
> [SCP-1491] feat: add businessunit and businessunits xml factories

- src/Factory/Xml/Product/ProductFactory.php
- src/Model/Product/BaseProduct.php
- src/Model/Product/GlobalProduct.php
Coverage:
gsc-master
```  
Classes: 93.28% (111/119)  
Methods: 97.78% (528/540)  
Lines:   93.81% (3107/3312)
```
fix/SCP-1495-modify-product-model
```
Classes: 93.28% (111/119)  
Methods: 97.78% (528/540)  
Lines:   93.81% (3108/3313)
```
> [SCP-1495] fix: remove status from base product and set the qcstatus in the global product factory

- docs/Managers/Product.md
- tests/Functional/ProductManagerTest.php
- tests/_schemas/Feed/ProductActionFeedResponse.xml
- tests/_schemas/Feed/ProductActionFeedResponseError.xml
Coverage:
gcs-master:
```
Classes: 93.28% (111/119)  
Methods: 97.78% (528/540)  
Lines:   93.81% (3107/3312)
```
feat/SCP-1530-modify-product-manager:
```
Classes: 93.28% (111/119)  
Methods: 97.78% (528/540)  
Lines:   93.81% (3107/3312)
```
> [SCP-1530] feat: modify product manager

- docs/Managers/Product.md
- tests/Functional/ProductManagerTest.php
Coverage:
gsc-master:
```
Classes: 93.28% (111/119)  
Methods: 97.78% (528/540)  
Lines:   93.81% (3108/3313)
```
feat/SCP-1535-modify-product-manager
```
Classes: 93.28% (111/119)  
Methods: 97.78% (528/540)  
Lines:   93.81% (3108/3313)
```
> [SCP-1535] feat: modify product manager

- src/Factory/Xml/Order/AddressFactory.php
- src/Factory/Xml/Order/OrdersItemsFactory.php
- tests/Functional/OrdersManagerTest.php
- tests/Unit/Order/AddressTest.php
- tests/Unit/Order/OrdersTest.php
- tests/_schemas/Order/Address.json
- tests/_schemas/Order/Address.xml
- tests/_schemas/Order/ErrorResponse.xml
Coverage:
gsc-master:
```
Classes: 93.28% (111/119)  
Methods: 97.78% (529/541)  
Lines:   93.56% (2978/3183)
```
feat/SCP-1518-implement-get-multiple-order-items:
```
Methods: 97.97% (530/541)  
Lines:   93.57% (2970/3174)
```
> [SCP-1518] refactor: add schemas and json files, refactor xml factories for order items and adress, refactor tests

- .github/workflows/CI.yml
- src/Factory/Xml/Product/ProductsFactory.php
- src/Formatter/LogMessageFormatter.php
- src/Service/ProductManager.php
- tests/Unit/Factory/ProductsFactoryTest.php
Coverage:
gsc-master:
```
Methods: 97.97% (530/541)  
Lines:   93.57% (2970/3174)
```
feat/SCP-1576-add-logs-for-the-structure-xml-errors
```
Methods: 97.97% (531/542)  
Lines:   93.58% (2975/3179)
```
> [SCP-1576] feat: add logger in the products factory and add branch to git worflows

- docs/Managers/Category.md
Small inconsistencies in documentation were adjusted
Previous documentation:
Endpoint Test:
> [SCP-1623] docs: Improve get categories by attributes set documentation

- src/Factory/Xml/Product/BusinessUnitFactory.php
- src/Factory/Xml/Product/ProductDataFactory.php
- src/Model/Product/BusinessUnit.php
- src/Model/Product/GlobalProduct.php
- tests/Functional/ProductManagerTest.php
- tests/Unit/Product/BusinessUnitTest.php
- tests/_schemas/Product/GlobalProductsResponse.xml
Coverage:
feat/SCP-1615-adapt-businnes-unit
```
Methods: 97.97% (531/542)  
Lines:   93.54% (2952/3156)
```
gsc-master
```
Methods: 97.97% (531/542)  
Lines:   93.58% (2975/3179)
```
> [SCP-1615] feat: adapt business unit model, factory and product model

- .github/dependabot.yml
- composer.lock
Coverage:
gsc-master:
```
Methods: 97.97% (531/542)  
Lines:   93.54% (2952/3156)
```
> [SCP-1644] feat: update gsc master branch with master

- src/Model/Product/BusinessUnit.php
- src/Model/Product/Contract/VariationProductInterface.php
- src/Model/Product/Product.php
- src/Service/ProductManager.php
- tests/Unit/Product/BusinessUnitTest.php
Coverage:
gsc-master:
```
Methods: 97.97% (531/542)  
Lines:   93.54% (2952/3156)
```
feat/scp-1726-gcs-sdk-improve-retro-compatibility:
```
Methods: 97.97% (531/542)  
Lines:   93.54% (2952/3156)
```
> [SCP-1726] feat: add variation interface for business unit and sc product

- src/Application/Configuration.php
- src/Service/BaseManager.php
- src/Service/BrandManager.php
- src/Service/CategoryManager.php
- src/Service/DocumentManager.php
- src/Service/FeedManager.php
- src/Service/GlobalProductManager.php
- src/Service/OrderManager.php
- src/Service/ProductManager.php
- src/Service/QualityControlManager.php
- src/Service/ShipmentManager.php
- src/Service/WebhookManager.php
Coverage:
feat/scp-1752-gsc-sdk-add-x-source-header-in-the-configuration
```
Methods: 98.19% (544/554)  
Lines:   94.06% (3278/3485)
```
gsc-master:
```
Methods: 98.22% (551/561)  
Lines:   94.34% (3236/3430)
```
> [SCP-1752] feat: gsc sdk add x source header in the configuration

- src/Factory/Xml/Product/GlobalProductsFactory.php
- src/Factory/Xml/Product/ProductDataFactory.php
- src/Model/Product/ProductData.php
- tests/Unit/Product/ProductDataTest.php
Coverage:
gsc-master:
```
Methods: 98.22% (551/561)  
Lines:   94.34% (3236/3430)
```
feat/SCP-1758-gsc-sdk-adapt-productdata-regarding-gsc:
```
Methods: 98.22% (551/561)  
Lines:   94.34% (3236/3430)
```
> [SCP-1758] feat: gsc sdk adapt productdata regarding gsc

- src/Service/OrderManager.php
- tests/Functional/OrdersManagerTest.php
- tests/_schemas/Order/ErrorResponse.xml
- tests/_schemas/Order/FailureReasonsSuccessResponse.xml
- tests/_schemas/Order/SetOrderStatusSuccessResponse.xml
Coverage:
gsc-master:
```
Methods: 98.19% (544/554)  
Lines:   94.05% (3274/3481)
```
feat/scp-1759-adapt-order-manager-set-status-to-ready-to-ship-method:
```
Methods: 98.19% (544/554)  
Lines:   94.06% (3276/3483)
```
> [SCP-1759] feat: adapt order manager set status to ready to ship method

- src/Contract/ProductStatus.php
- src/Model/Product/BusinessUnit.php
- src/Model/Product/Contract/VariationProductInterface.php
- src/Model/Product/Product.php
- src/SellerCenterSdk.php
- src/Service/Contract/ProductManagerInterface.php
- src/Service/GlobalProductManager.php
- src/Service/ProductManager.php
- tests/Unit/Service/GlobalProductManagerTest.php
- tests/Unit/Service/ProductManagerTest.php
Coverage:
gsc-master-dev:
```
Methods: 98.19% (544/554)  
Lines:   94.06% (3276/3483)
```
feat/scp-1819-gsc-sdk-add-a-product-manager-interface-to-unify-product-managers:
```
Methods: 98.19% (544/554)  
Lines:   94.05% (3274/3481)
```
> [SCP-1819] feat:  Add ProductManagerInterface to unify product managers

- src/Service/OrderManager.php
- tests/Functional/OrdersManagerTest.php
- tests/_schemas/Order/SetInvoiceNumberSuccessResponse.xml
Coverage:
Current Branch:
```
Methods: 98.21% (549/559)  
Lines:   94.12% (3311/3518)
```
Master Branch:
```
Methods: 98.21% (548/558)  
Lines:   94.09% (3293/3500)
```
> [SCP-2244] Feat: gsc sdd add support for set invoice number endpoint

- src/Model/Product/BusinessUnit.php
- src/Model/Product/GlobalProduct.php
- src/Service/OrderManager.php
- src/Transformer/Product/ProductTransformer.php
- tests/Unit/Product/GlobalProductsTest.php
to deactivate a product it is only necessary to send the sellersku and the business unit with the inactive status to gsc
**Current branch:**
```
Classes: 95.08% (116/122)
Methods: 98.21% (549/559)
Lines:   94.12% (3312/3519
```
**GSC-Master-Dev branch:**
```
Classes: 95.08% (116/122)
Methods: 98.21% (549/559)
Lines:   94.12% (3312/3519)
```
[https://jira.falabella.com/browse/SCP-2240](https://jira.falabella.com/browse/SCP-2240)
**Subtasks:**
- [https://jira.falabella.com/browse/SCP-2315](https://jira.falabella.com/browse/SCP-2315)
> [SCP-2315] feat: add support to disable global product

- src/Factory/Xml/Product/GlobalProductFactory.php
- src/Model/Product/Attribute.php
- src/Model/Product/BaseProduct.php
- src/Model/Product/BusinessUnit.php
- src/Model/Product/Contract/FashionInterface.php
- src/Model/Product/Contract/ProductInterface.php
- src/Model/Product/GlobalProduct.php
- tests/Unit/Product/GlobalProductTest.php
- tests/Unit/Transformer/Product/ProductTransfomerTest.php
- tests/_schemas/Product/GlobalProduct.json
- tests/_schemas/Product/GlobalProductFashionAttributes.xml
- tests/_schemas/Product/GlobalProductOptionalVariations.xml
references:
https://jira.falabella.com/browse/SCP-2379
Current branch:
```
Classes: 94.26% (115/122)  
Methods: 98.07% (558/569)  
Lines:   94.16% (3353/3561)
```
gsc-master-dev:
```
Classes: 93.44% (114/122)  
Methods: 97.86% (549/561)  
Lines:   94.08% (3322/3531)
```
> [SCP-2379] feat: support fashion category attributes

- src/Contract/ProductConditionTypes.php
> [SCP-3132] fix: Updated ConditionType values for validation

- docs/Managers/GlobalOrderManager.md
- src/Service/BaseOrderManager.php
- src/Service/GlobalOrderManager.php
- tests/Functional/GlobalOrderManagerTest.php
- tests/_schemas/Order/InvoiceDocument.xml
- tests/_schemas/Order/SetInvoiceDocumentSuccessResponse.xml
Coverage:
Current Branch:
```
Classes: 95.31% (122/128)  
Methods: 98.32% (586/596)  
Lines:   94.16% (3388/3598)
```
Master Branch:
```
Classes: 95.31% (122/128)  
Methods: 98.32% (585/595)  
Lines:   94.13% (3369/3579)
```
> [SCP-3353] feat: add SetInvoiceDocument action to the GlobalOrdersManager

- README.md
- src/Application/Configuration.php
- src/Application/Parameters.php
- src/SellerCenterSdk.php
- src/Service/BaseManager.php
- tests/Unit/Application/ConfigurationTest.php
- tests/Unit/Application/ParametersTest.php
current branch
```
Classes: 95.42% (125/131)
Methods: 98.37% (604/614)
Lines:   94.27% (3458/3668)
```
gsc-master-dev
```
Classes: 95.42% (125/131)
Methods: 98.35% (597/607)
Lines:   94.22% (3424/3634)
```
> [SCP-3524] feat: add support for user agent

- src/Formatter/LogMessageFormatter.php
- src/Service/BaseManager.php
- src/Service/BaseOrderManager.php
- src/Service/BrandManager.php
- src/Service/CategoryManager.php
- src/Service/DocumentManager.php
- src/Service/FeedManager.php
- src/Service/GlobalOrderManager.php
- src/Service/GlobalProductManager.php
- src/Service/OrderManager.php
- src/Service/ProductManager.php
- src/Service/QualityControlManager.php
- src/Service/ShipmentManager.php
- src/Service/WebhookManager.php
- tests/Functional/BaseOrderManagerTest.php
- tests/Unit/Service/BaseManagerTest.php
Current Branch:
```
Classes: 95.42% (125/131)  
Methods: 98.37% (602/612)  
Lines:   95.25% (3246/3408)
```
Gsc-master-dev:
```
Classes: 95.42% (125/131)  
Methods: 98.37% (604/614)  
Lines:   94.27% (3458/3668)
```
> [SCP-3612] fix: remove unnecesary logs

- src/Service/BaseManager.php
- src/Service/BaseOrderManager.php
- src/Service/BaseSellerManager.php
- src/Service/BrandManager.php
- src/Service/CategoryManager.php
- src/Service/DocumentManager.php
- src/Service/FeedManager.php
- src/Service/GlobalOrderManager.php
- src/Service/GlobalProductManager.php
- src/Service/GlobalSellerManager.php
- src/Service/OrderManager.php
- src/Service/ProductManager.php
- src/Service/QualityControlManager.php
- src/Service/ShipmentManager.php
- src/Service/WebhookManager.php
- tests/Unit/Service/BaseManagerTest.php
Coverage:
Current:
```
Classes: 97.01% (130/134)  
Methods: 99.37% (628/632)  
Lines:   99.60% (3024/3036)
```
Gsc-Master-Dev:
```
Classes: 97.01% (130/134)  
Methods: 99.36% (625/629)  
Lines:   99.66% (3474/3486)
```
> [SCP-3647] refactor: use common methods from the base manager in all managers

- docker/Dockerfile
- docs/Managers/GlobalOrderManager.md
- src/Service/GlobalOrderManager.php
- tests/Functional/GlobalOrderManagerTest.php
- tests/Functional/GlobalProductManagerTest.php
- tests/Functional/ProductManagerTest.php
coverage:
Current:
```
Classes: 97.01% (130/134)  
Methods: 99.37% (628/632)  
Lines:   99.60% (3024/3036)
```
Gsc-Master-Dev:
```
Classes: 97.01% (130/134)  
Methods: 99.37% (628/632)  
Lines:   99.60% (3024/3036)
```
> [SCP-3799] feat: modify set invoice number endpoint to work with array of item ids

- src/Service/GlobalOrderManager.php
- tests/Functional/GlobalOrderManagerTest.php
Coverage:
Current Branch:
```
Classes: 97.01% (130/134)  
Methods: 99.37% (628/632)  
Lines:   99.61% (3028/3040)
```
Gsc-Master-Dev Branch:
```
Classes: 97.01% (130/134)  
Methods: 99.37% (628/632)  
Lines:   99.60% (3024/3036)
```
> [SCP-3899] feat: sdk php update set invoice document in sdk global order manager

- src/Service/GlobalOrderManager.php
**Current branch unit test coverage**
```
Classes: 97.16% (137/141)  
Methods: 99.39% (653/657)  
Lines:   99.62% (3156/3168)
```
> [SCP-4132] fix: Change route to set invoice pdf endpoint
